// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
package main

import (
	"encoding/json"
	"net/http"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

// Resume ...
type Resume struct {
	Basics       Basics      `json:"basics"`
	Education    []Education `json:"education"`
	Work         []Work      `json:"work"`
	Projects     []Project   `json:"projects"`
	Volunteer    []Volunteer `json:"volunteer"`
	Awards       []string    `json:"awards"`
	Publications []string    `json:"publications"`
	Skills       []Skill     `json:"skills"`
	Languages    []Language  `json:"languages"`
	Interests    []Interest  `json:"interests"`
}

// Basics ...
type Basics struct {
	Name     string    `json:"name"`
	Label    string    `json:"label"`
	Picture  string    `json:"picture"`
	Email    string    `json:"email"`
	Phone    string    `json:"phone"`
	Website  string    `json:"website"`
	Summary  string    `json:"summary"`
	Location Location  `json:"location"`
	Profiles []Profile `json:"profiles"`
}

// Location ...
type Location struct {
	Address     string `json:"address"`
	PostalCode  string `json:"postalCode"`
	City        string `json:"city"`
	CountryCode string `json:"countryCode"`
	Region      string `json:"region"`
}

// Profile ...
type Profile struct {
	Network  string `json:"network"`
	Username string `json:"username"`
	URL      string `json:"url"`
}

// Education ...
type Education struct {
	Institution string   `json:"institution"`
	Area        string   `json:"area"`
	StudyType   string   `json:"studyType"`
	StartDate   string   `json:"startDate"`
	EndDate     string   `json:"endDate"`
	Gpa         string   `json:"gpa"`
	Courses     []string `json:"courses"`
}

// Interest ...
type Interest struct {
	Name     string   `json:"name"`
	Keywords []string `json:"keywords"`
}

// Language ...
type Language struct {
	Language string `json:"language"`
	Fluency  string `json:"fluency"`
}

// Project ...
type Project struct {
	Name     string   `json:"name"`
	Position string   `json:"position"`
	Info     []string `json:"info"`
}

// Skill ...
type Skill struct {
	Name     string   `json:"name"`
	Level    string   `json:"level"`
	Keywords []string `json:"keywords"`
}

// Work ...
type Work struct {
	Company    string   `json:"company"`
	Position   string   `json:"position"`
	Website    string   `json:"website"`
	StartDate  string   `json:"startDate"`
	EndDate    string   `json:"endDate"`
	Summary    string   `json:"summary"`
	Highlights []string `json:"highlights"`
}

// Volunteer ...
type Volunteer struct {
	Organization string   `json:"organization"`
	Position     string   `json:"position"`
	Website      string   `json:"website"`
	StartDate    string   `json:"startDate"`
	EndDate      string   `json:"endDate"`
	Summary      string   `json:"summary"`
	Highlights   []string `json:"highlights"`
}

func getResume() *Resume {
	return &Resume{
		Basics: Basics{
			Name:    "Irving Lopez Serna",
			Label:   "Backend Developer",
			Picture: "",
			Email:   "",
			Phone:   "",
			Website: "https://irvinglopez.xyz/",
			Summary: "Backend Developer. I'm a passionate and detail oriented full stack software developer based in Yorktown Heights, New York. I enjoy turning problems into solutions that make people smile. I enjoy continuous learning and exploring new technologies. When I'm not coding at home or work, I enjoy time with my family.",
			Location: Location{
				Address:     "",
				PostalCode:  "",
				City:        "Yorktown Heights",
				CountryCode: "US",
				Region:      "New York",
			},
			Profiles: []Profile{
				{
					Network:  "Linkedin",
					Username: "Irving Lopez Serna",
					URL:      "https://www.linkedin.com/in/donirv64",
				}, {
					Network:  "GitHub",
					Username: "ilopez64",
					URL:      "https://github.com/ilopez64",
				},
			},
		},
		Education: []Education{
			{
				Institution: "Manhattan College",
				Area:        "Computer Science",
				StudyType:   "Masters",
				StartDate:   "2019-08-26",
				EndDate:     "2020-05-13",
				Gpa:         "4.0/4.0",
				Courses:     []string{},
			},
			{
				Institution: "Manhattan College",
				Area:        "Computer Science",
				StudyType:   "Bachelor",
				StartDate:   "2015-08-26",
				EndDate:     "2019-05-17",
				Gpa:         "3.0/4.0",
				Courses:     []string{},
			},
		},
		Work: []Work{
			{
				Company:   "Manhattan College ITS",
				Position:  "ITS Operations",
				Website:   "https://www.manhattan.edu",
				StartDate: "2015-08-26",
				EndDate:   "2016-05-13",
				Summary:   "As a member of the Operations group in the ITS Department, I aided in the management of all campus computers.",
				Highlights: []string{
					"Handled issues college students and faculty faced regarding computers and network issues.",
					"Updated software on college computers.",
					"Performed weekly check ups on all campus smart labs.",
				},
			},
		},
		Projects: []Project{
			{
				Name:     "Positifeedy",
				Position: "iOS Developer",
				Info: []string{
					"App which gives users a feed of mental health and mindfulness content. Meant to be a supplement for mental health therapy.",
					"Utilizes Google Firebase for sign-in, data storage, and notifications.",
					"Winner of 2017 Manhattan College Business Innovation Contest.",
				},
			},
			{
				Name:     "Online Shop",
				Position: "Backend API Developer",
				Info: []string{
					"Created backend RESTFUL API for online shop with the Django framework using a MySQL database.",
					"Used the Heroku platform for deployment.",
				},
			},
			{
				Name:     "Toy Bittorrent",
				Position: "Software Developer",
				Info: []string{
					"A partner and I created a very basic version of Bittorrent where files can easily be shared.",
					"Project written completely in Python.",
				},
			},
		},
		Volunteer: []Volunteer{
			{
				Organization: "Alliance for Safe Kids",
				Position:     "Social Media Manager/Community Organizer",
				Website:      "https://allianceforsafekids.org/",
				StartDate:    "2014-05-10",
				EndDate:      "2016-08-02",
				Summary:      "Alliance for Safe Kids (ASK) is a local non-profit that promotes a drug free like to children and teens.",
				Highlights: []string{
					"Managed the social media presence for ASK.",
					"Ran a community event involving over 50 small businesses.",
				},
			},
		},
		Awards:       []string{},
		Publications: []string{},
		Skills: []Skill{
			{
				Name:     "Python",
				Level:    "Pro",
				Keywords: []string{},
			}, {
				Name:  "Django",
				Level: "Pro",
				Keywords: []string{
					"REST API",
				},
			}, {
				Name:  "JavaScript",
				Level: "Intermediate",
				Keywords: []string{
					"ECMAScript", "ES6", "Node.js", "Web", "Front End",
				},
			}, {
				Name:  "React",
				Level: "Intermediate",
				Keywords: []string{
					"SPA", "Web", "Front End",
				},
			}, {
				Name:  "AWS",
				Level: "Intermediate",
				Keywords: []string{
					"Cloud", "Lambda", "S3",
				},
			}, {
				Name:  "IBMCloud",
				Level: "Pro",
				Keywords: []string{
					"Cloud Foundry", "Cloud Object Storage", "Cloudant",
				},
			}, {
				Name:  "Go",
				Level: "Intermediate",
				Keywords: []string{
					"Golang",
				},
			}, {
				Name:  "SQL",
				Level: "Pro",
				Keywords: []string{
					"PostgreSQL", "MySQL",
				},
			}, {
				Name:  "NOSQL",
				Level: "Intermediate",
				Keywords: []string{
					"MongoDB",
				},
			}, {
				Name:  "Kubernetes",
				Level: "Intermediate",
				Keywords: []string{
					"K8s",
				},
			}, {
				Name:  "Docker",
				Level: "Pro",
				Keywords: []string{
					"Containers",
				},
			}, {
				Name:  "Linux",
				Level: "Intermediate",
				Keywords: []string{
					"Bash", "Shell",
				},
			}, {
				Name:  "GitHub",
				Level: "Expert",
				Keywords: []string{
					"SDLC", "OSS", "CI/CD",
				},
			}, {
				Name:  "GitLab",
				Level: "Expert",
				Keywords: []string{
					"SDLC", "OSS", "CI/CD",
				},
			}, {
				Name:  "Pipelines",
				Level: "Expert",
				Keywords: []string{
					"DevOps",
				},
			}, {
				Name:     "Java",
				Level:    "Intermediate",
				Keywords: []string{},
			}, {
				Name:     "C++",
				Level:    "Intermediate",
				Keywords: []string{},
			},
		},
		Languages: []Language{
			{
				Language: "English",
				Fluency:  "Native speaker",
			},
			{
				Language: "Spanish",
				Fluency:  "Native speaker",
			},
			{
				Language: "French",
				Fluency:  "Basic proficiency",
			},
		},
		Interests: []Interest{
			{
				Name: "Dance",
				Keywords: []string{
					"Hip Hop", "Breakdance", "Salsa",
				},
			}, {
				Name: "Photography",
				Keywords: []string{
					"Weddings", "Landscape", "Senior",
				},
			},
		},
	}
}

// Formatting the response JSON
func (input Resume) formatResume() string {
	formattedResume, _ := json.MarshalIndent(input, "", "  ")
	return string(formattedResume)
}

// Serving the API using AWS API Gateway and Lambda
func handleRequest(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	resume := getResume()
	formattedResume := resume.formatResume()

	response := events.APIGatewayProxyResponse{
		StatusCode: http.StatusOK,
		Headers:    map[string]string{"Content-Type": "application/json"},
		Body:       formattedResume,
	}
	return response, nil
}

// Main function to handle requests by calling handleRequest
func main() {
	lambda.Start(handleRequest)
}
